# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd6937b42f171ff072a8ca7c9cc66be73c013494159fd262b1a1bdbae7012aec7a43b268766a460ccf624e9eefdb917987d9a56100cfb69cbb4b6ed6862e698a

test:
  secret_key_base: f62c1587f0e03ee55b2609d924528337be28e5ca7b47fbe7b151f9d50ffd9e2bab088dafb12e74046a9c44623651950e19a1dbfb838e61af195cc3a80a3fa8f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
